name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v .

      - name: Test
        run: |
          go test -race -v -coverprofile=coverage.out -covermode=atomic ./...
          bash <(curl --connect-timeout 10 --retry 5 -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}


      - name: Notify Go Report Card
        run: curl --connect-timeout 10 --retry 5 -XPOST https://goreportcard.com/checks -F 'repo=github.com/muhammadhabibullah/book-management-system'
